import { Bell, Menu, Search, WalletCards, Activity } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { cn } from '@/lib/utils';

const labels: Record<string, string> = { '/dashboard': 'Overview', '/offerwalls': 'Earn rewards', '/leaderboard': 'Leaderboard', '/achievements': 'Achievements', '/history': 'Activity', '/referrals': 'Referrals', '/wallet': 'Wallet', '/withdraw': 'Withdraw', '/profile': 'Profile', '/settings': 'Settings', '/support': 'Support', '/admin': 'Admin console' };
export function TopBar({ onMenuClick }: { onMenuClick: () => void }) {
  const { profile } = useAuth(); const location = useLocation(); const displayName = profile?.username || profile?.name || 'Member'; const initials = displayName.slice(0, 2).toUpperCase();
  return <header className="hud-topbar"><div className="flex min-w-0 items-center gap-3"><button onClick={onMenuClick} className="focus-ring rounded-xl p-2 text-muted-foreground hover:bg-white/5 hover:text-foreground lg:hidden" aria-label="Open navigation"><Menu className="h-5 w-5" /></button><div className="hidden items-center gap-3 sm:flex"><span className="hud-status-dot" /><span className="hud-label">RewardsVerse /</span><span className="truncate font-display text-sm font-semibold text-foreground">{labels[location.pathname] || 'Command center'}</span></div><div className="flex items-center gap-2 sm:hidden"><Activity className="h-4 w-4 text-primary" /><span className="font-display font-semibold text-foreground">{labels[location.pathname] || 'RewardsVerse'}</span></div></div><div className="flex items-center gap-2 sm:gap-3"><span className="hidden font-mono text-[9px] uppercase tracking-[.18em] text-primary/70 xl:block">SYS // ONLINE</span><label className="hud-search hidden lg:flex" aria-label="Search rewards"><Search className="h-4 w-4 shrink-0 text-primary" /><input placeholder="Search rewards..." /></label><button className="focus-ring relative rounded-xl border border-primary/15 p-2.5 text-muted-foreground transition hover:border-primary/35 hover:bg-primary/5 hover:text-foreground" aria-label="Notifications"><Bell className="h-[17px] w-[17px]" /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-primary shadow-[0_0_8px_var(--primary)]" /></button><Link to="/wallet" className="focus-ring flex items-center gap-2 rounded-xl border border-primary/25 bg-primary/8 px-3 py-2 transition hover:bg-primary/15"><WalletCards className="h-4 w-4 text-primary" /><span className="hidden text-xs text-muted-foreground sm:inline">Balance</span><span className="font-display text-sm font-semibold text-primary">${Number(profile?.balance || 0).toFixed(2)}</span></Link><Link to="/profile" className="focus-ring hidden items-center gap-2 border-l border-primary/15 pl-3 sm:flex"><span className={cn('flex h-8 w-8 items-center justify-center rounded-full border border-primary/35 bg-primary/10 text-xs font-bold text-primary')}>{initials}</span><span className={cn('max-w-[100px] truncate text-sm font-medium', !profile && 'text-muted-foreground')}>{displayName}</span></Link></div></header>;
}
