import { ArrowRight, CheckCircle2, Clock3, Gift, ShieldCheck, WalletCards, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { trpc } from '@/lib/trpc';
import { EmptyState, LoadingRows, SectionHeading, Surface } from '@/components/shared/RewardUI';

const steps = [
  { icon: Gift, title: 'Choose an offer', text: 'Browse available surveys, apps and tasks from configured providers.' },
  { icon: Clock3, title: 'Complete and verify', text: 'Provider verification keeps earnings and balance activity transparent.' },
  { icon: WalletCards, title: 'Withdraw clearly', text: 'Track your balance and submit an eligible LTC or Binance payout.' },
];

export default function HomePage() {
  const featured = trpc.user.getFeaturedOffers.useQuery(undefined, { staleTime: 60_000, refetchOnWindowFocus: false });
  return <div className="mx-auto w-full max-w-[1280px] space-y-8 px-4 py-6 sm:px-6 lg:px-8 lg:py-10">
    <section className="overflow-hidden rounded-[1.75rem] border border-border bg-white shadow-[0_20px_60px_rgba(15,23,42,.08)]"><div className="grid items-center gap-10 bg-gradient-to-br from-white via-slate-50 to-emerald-50/70 px-6 py-12 sm:px-10 lg:grid-cols-[1.1fr_.9fr] lg:py-16"><div><div className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><Zap className="h-3.5 w-3.5" /> A focused rewards platform</div><h1 className="mt-5 max-w-2xl font-display text-4xl font-bold leading-[1.04] tracking-[-0.06em] text-slate-950 sm:text-6xl">Earn more. <span className="text-emerald-600">Reward yourself.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">RewardsVerse brings verified surveys, apps, games and tasks into one clear earn center—with balance and payout activity you can follow.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-slate-900/10 hover:bg-slate-800">Start earning <ArrowRight className="h-4 w-4" /></Link><Link to="/offerwalls" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">Explore earn center</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-600" /> Transparent activity</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600" /> Verified provider callbacks</span></div></div><div className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-2xl shadow-slate-900/10 sm:p-6"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs text-slate-400">Your earning command center</p><p className="mt-1 font-display text-lg font-semibold">One clear next step</p></div><span className="rounded-lg bg-emerald-400/15 p-2 text-emerald-300"><Zap className="h-4 w-4" /></span></div><div className="mt-5 space-y-3">{steps.map(({ icon: Icon, title, text }, index) => <div key={title} className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-400/10 text-emerald-300"><Icon className="h-4 w-4" /></div><div className="min-w-0"><p className="text-sm font-semibold">{index + 1}. {title}</p><p className="mt-1 text-xs leading-5 text-slate-400">{text}</p></div></div>)}</div></div></div></section>
    <div className="grid gap-4 md:grid-cols-3">{[{ icon: ShieldCheck, title: 'Built on transparency', text: 'See activity, statuses and balance movement without guesswork.' }, { icon: Zap, title: 'Start with one action', text: 'A focused earn center keeps discovery simple and useful.' }, { icon: WalletCards, title: 'Payout clarity', text: 'Supported withdrawal methods and minimums are shown before submission.' }].map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-4 w-4" /></div><h2 className="mt-4 text-sm font-semibold text-slate-900">{title}</h2><p className="mt-1.5 text-sm leading-6 text-slate-500">{text}</p></div>)}</div>
    <Surface className="p-5 sm:p-6"><SectionHeading eyebrow="Live opportunity feed" title="Featured offers" description="Start with offers from the current RewardsVerse catalog." action={<Link to="/offerwalls" className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-700">View earn center <ArrowRight className="h-4 w-4" /></Link>} /><div className="mt-6">{featured.isLoading ? <LoadingRows count={3} /> : featured.data?.length ? <div className="grid gap-3 md:grid-cols-3">{featured.data.slice(0, 3).map((offer: any) => <Link key={`${offer.provider}-${offer.offerName}`} to="/offerwalls" className="rounded-xl border border-border bg-slate-50 p-4 transition hover:-translate-y-0.5 hover:border-emerald-300 hover:bg-emerald-50/40"><p className="text-sm font-semibold text-slate-900">{offer.offerName || `${offer.provider} offer`}</p><p className="mt-1 text-xs text-slate-500">{offer.provider}</p><div className="mt-4 flex items-center justify-between text-xs"><span className="text-slate-500">{offer.completionCount || 0} completions</span><span className="font-semibold text-emerald-700">Avg. ${Number(offer.averageReward || 0).toFixed(2)}</span></div></Link>)}</div> : <EmptyState title="Your earn center is ready" description="Sign in to explore configured providers and personalized offers." action={<Link to="/login" className="text-sm font-semibold text-emerald-700">Sign in to continue</Link>} />}</div></Surface>
  </div>;
}
