import { ArrowDownToLine, ArrowRight, Award, Bell, CheckCircle2, CircleDollarSign, Clock3, Gift, LayoutDashboard, LifeBuoy, Menu, Settings, ShieldCheck, UserRound, WalletCards, Zap } from 'lucide-react';
import { OFFER_WALLS } from './OfferWalls';
import '../preview.css';

const mockOffers = [
  ['Complete a quick survey', 'CPX Research', '$0.10–$5.00', 'Surveys'],
  ['Install and try a new app', 'Revtoo', '$0.25–$8.00', 'Apps'],
  ['Play a casual game', 'GemiWall', '$0.10–$5.00', 'Games'],
  ['Join a rewards program', 'Offerwall.me', '$0.10–$10.00', 'Tasks'],
  ['Answer a short questionnaire', 'TimeWall', '$0.10–$8.00', 'Surveys'],
  ['Try a premium mobile app', 'Moustache Leads', '$0.50–$10.00', 'Apps'],
  ['Finish an engagement task', 'Taskwall', '$0.15–$6.00', 'Tasks'],
  ['Complete a crypto offer', 'Cointo', '$0.20–$4.00', 'Apps'],
  ['Explore a new finance app', 'Klink Labs', '$0.30–$7.00', 'Apps'],
  ['Take a rewarded survey', 'TheoremReach', '$0.10–$5.00', 'Surveys'],
];

function money(value: string) { return value; }

export default function PreviewPage() {
  return <div className="preview-shell">
    <aside className="preview-sidebar"><div className="preview-brand"><span className="preview-brand-mark"><Zap className="h-4 w-4" /></span><strong>RewardsVerse</strong></div><nav className="preview-nav"><p>COMMAND CENTER</p><a className="active"><LayoutDashboard className="h-4 w-4" />Dashboard</a><p>YOUR REWARDS</p><a><Gift className="h-4 w-4" />Earn rewards</a><a><Award className="h-4 w-4" />Leaderboard</a><a><Clock3 className="h-4 w-4" />Activity</a><a><WalletCards className="h-4 w-4" />Withdraw</a><p>ACCOUNT</p><a><UserRound className="h-4 w-4" />Profile</a><a><Settings className="h-4 w-4" />Settings</a><a><LifeBuoy className="h-4 w-4" />Support</a></nav><div className="preview-user"><span className="preview-avatar">J</span><span><strong>Preview member</strong><small>Level 4 member</small></span></div></aside>
    <main className="preview-main"><header className="preview-topbar"><button className="preview-menu"><Menu className="h-4 w-4" /></button><div className="preview-top-actions"><button><Bell className="h-4 w-4" /></button><span className="preview-balance"><CircleDollarSign className="h-4 w-4" /> $12.45</span><span className="preview-avatar small">J</span></div></header><div className="preview-live"><span className="preview-dot" /><span>Verified activity</span><span className="preview-live-track">Sarah completed a survey · Michael earned $2.40 · New provider offers available</span></div><div className="preview-content"><section className="preview-welcome"><div><span className="preview-eyebrow"><span className="preview-dot" /> Your rewards workspace</span><h1>Good to see you, <em>Jordan</em></h1><p>Earn rewards from verified surveys, apps, games and tasks, then follow every balance and payout update in one clear place.</p><div className="preview-actions"><button><Zap className="h-4 w-4" /> Start earning <ArrowRight className="h-4 w-4" /></button><button className="secondary"><WalletCards className="h-4 w-4" /> Withdraw</button></div></div><div className="preview-next"><span>YOUR NEXT STEP</span><strong>Choose an offer</strong><p>Browse live providers and complete a verified offer.</p><div><b>01</b> Browse live providers</div><div><b>02</b> Complete and verify</div><div><b>03</b> Withdraw clearly</div></div></section>
      <section className="preview-section featured-primary"><div className="preview-section-head"><div><span className="preview-eyebrow"><span className="preview-dot" /> Offer catalog</span><h2>Featured offers</h2><p>Start with live offers from the current provider feed.</p></div><span className="preview-search">Search offers…</span></div><div className="preview-filters"><span className="selected">Featured</span><span>Highest Reward</span><span>Surveys</span><span>Apps</span><span>Games</span><span>Easy Tasks</span></div><div className="preview-offer-grid">{mockOffers.map(([title, provider, reward, category], index) => <a className="preview-offer-card" key={title}><div className="preview-card-top"><span className="preview-offer-logo">{provider.slice(0, 1)}</span><small>AVAILABLE</small></div><div><span className="preview-category">{category}</span><span className="preview-provider">{provider}</span><h3>{title}</h3><p>Open the provider offer to see the current requirements.</p></div><div className="preview-card-bottom"><span><small>REWARD</small><strong>{money(reward)}</strong></span><b>Start offer <ArrowRight className="h-3 w-3" /></b></div></a>)}</div></section>
      <section className="preview-stat-row"><div><WalletCards /><span>AVAILABLE BALANCE<strong>$12.45</strong><small>Ready to withdraw</small></span><button>Withdraw balance</button></div><div><CheckCircle2 /><span>OFFERS COMPLETED<strong>24</strong><small>Verified completions</small></span></div><div><Award /><span>TOTAL EARNED<strong>$48.72</strong><small>All-time rewards</small></span></div><div><Clock3 /><span>PENDING POINTS<strong>$3.20</strong><small>Awaiting verification</small></span></div></section>
      <section className="provider-rail preview-provider-rail"><div className="provider-rail-heading"><div><p className="rv-eyebrow">Reward network</p><h2>Offer wall partners</h2><p>18 providers arranged in two balanced rows.</p></div><span className="provider-rail-count">18 walls</span></div><div className="provider-rail-grid">{OFFER_WALLS.map((wall) => <a key={wall.id} className="provider-mini-card" style={{ borderColor: wall.border }}><span className="provider-mini-logo">{wall.logo ? <img src={wall.logo} alt="" /> : wall.name.slice(0, 1)}</span><span className="provider-mini-copy"><strong>{wall.name}</strong><span>{wall.tag} · {wall.reward}</span></span><span className="provider-mini-status is-ready" /></a>)}</div></section>
      <section className="preview-profile"><div><span className="preview-eyebrow">Profile rewards hub</span><h2>Offers, points and withdrawals</h2><p>A complete view of the account-related reward information.</p></div><div className="preview-profile-cards"><div><WalletCards /><span>Available balance<strong>$12.45</strong><a>Withdraw now <ArrowDownToLine className="h-3 w-3" /></a></span></div><div><Award /><span>Total earned<strong>$48.72</strong><small>24 offers completed</small></span></div><div><Clock3 /><span>Pending points<strong>$3.20</strong><small>Awaiting verification</small></span></div><div><ArrowDownToLine /><span>Withdrawals<strong>2</strong><small>View activity</small></span></div></div></section></div></main>
  </div>;
}
